---
sidebar: sidebar 
permalink: workflows_infra/workflows_infra_before.html 
keywords:  
summary:  
---
= Prima di iniziare
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare questi flussi di lavoro per creare e gestire l'infrastruttura utilizzata con il modello di implementazione di Astra Control Center. Nella maggior parte dei casi, i flussi di lavoro possono essere utilizzati anche con Astra Control Service.


NOTE: Questi flussi di lavoro possono essere ampliati e migliorati da NetApp in qualsiasi momento, pertanto è necessario esaminarli periodicamente.



== Preparazione generale

Prima di utilizzare uno qualsiasi dei flussi di lavoro Astra, assicurarsi di rivedere link:../get-started/prepare_to_use_workflows.html["Preparati a utilizzare i flussi di lavoro"].



== Categorie di workflow

I flussi di lavoro dell'infrastruttura sono organizzati in diverse categorie per facilitare l'individuazione di quello desiderato.

[cols="25,75"]
|===
| Categoria | Descrizione 


| Identità e accesso | Questi flussi di lavoro consentono di gestire l'identità e l'accesso ad Astra. Le risorse includono utenti, credenziali e token. 


| Bucket | È possibile utilizzare questi flussi di lavoro per creare e gestire i bucket S3 utilizzati per memorizzare i backup. 


| Storage | Questi flussi di lavoro consentono di aggiungere e gestire volumi e backend di storage. 


| Cluster | È possibile aggiungere cluster Kubernetes gestiti che consentono di proteggere e supportare le applicazioni in essi contenute. 
|===