---
sidebar: sidebar 
permalink: workflows/wf_list_unman_apps.html 
keywords:  
summary:  
---
= Elencare le applicazioni non gestite
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile elencare le applicazioni attualmente non gestite da Astra. Questa operazione potrebbe essere eseguita durante la selezione di un'applicazione da gestire.


NOTE: L'endpoint REST utilizzato in questi flussi di lavoro restituisce tutte le applicazioni Astra per impostazione predefinita. È possibile utilizzare `filter` Parametro di query sulla chiamata API per richiedere la restituzione delle sole applicazioni non gestite. In alternativa, è possibile omettere il parametro di filtro per restituire tutte le applicazioni e quindi esaminare `managedState` nel campo di output per determinare quali applicazioni sono presenti in `unmanaged` stato.



== Elencare solo le applicazioni con managedState uguale a non gestite

Questo flusso di lavoro utilizza `filter` parametro di query per restituire solo le applicazioni non gestite.



=== 1. Elencare le applicazioni non gestite

Eseguire la seguente chiamata API REST.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /Account/{AccountID}/topology/v1/apps 
|===


===== Parametri di input aggiuntivi

Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| filtro | Query | No | Utilizza un filtro per specificare quali app devono essere restituite. 


| includi | Query | No | Se si desidera, selezionare i valori che si desidera restituire nella risposta. 
|===


===== Esempio di curl: Restituisce nome, id e managedState per le applicazioni non gestite

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?filter=managedState%20eq%20'unmanaged'&include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Esempio di output JSON

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ]
  ],
  "metadata": {}
}
----


== Elencare tutte le applicazioni e selezionare quelle non gestite

Questo flusso di lavoro restituisce tutte le applicazioni. È necessario esaminare l'output per determinare quali non sono gestiti.



=== 1. Elencare tutte le applicazioni

Eseguire la seguente chiamata API REST.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /Account/{AccountID}/topology/v1/apps 
|===


===== Parametri di input aggiuntivi

Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| includi | Query | No | Se si desidera, selezionare i valori che si desidera restituire nella risposta. 
|===


===== Esempio di curl: Restituisce tutti i dati per tutte le applicazioni

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Esempio di curl: Restituisce nome, id e managedState per tutte le applicazioni

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Esempio di output JSON

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "mariadb-mariadb",
      "8da20fff-c69c-4170-bb0d-e4f91c5a1333",
      "managed"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ],
    [
      "davidns-postgres-app",
      "11e046b7-ec64-4184-85b3-debcc3b1da4d",
      "managed"
    ]
  ],
  "metadata": {}
}
----


=== 2. Selezionare le applicazioni non gestite

Esaminare l'output della chiamata API e selezionare manualmente le applicazioni con `managedState` uguale a. `unmanaged`.
