---
sidebar: sidebar 
permalink: workflows/wf_list_backups.html 
keywords:  
summary:  
---
= Elencare i backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile elencare i backup creati per una specifica applicazione gestita.



=== Prima di iniziare

È necessario disporre dell'ID dell'applicazione gestita per cui si desidera elencare i backup. Se necessario, è possibile utilizzare il flusso di lavoro link:wf_list_man_apps.html["Elencare le applicazioni gestite"] per individuare l'applicazione.



=== 1. Elencare i backup

Eseguire la seguente chiamata API REST.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /Accounts/{account_id}/k8s/v1/managedApps/{managedApp_id}/appBackups 
|===


===== Parametri di input aggiuntivi

Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| id app gestito | Percorso | Sì | Identifica l'applicazione gestita proprietaria dei backup elencati. 
|===


===== Esempio di curl: Restituire tutti i backup per l'applicazione

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appBackups' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Esempio di output JSON

[source, json]
----
{
  "items": [
    {
      "type": "application/astra-appBackup",
      "version": "1.0",
      "id": "ed39fdb0-12db-497b-9e46-20036c1fb0d2",
      "name": "mariadb-mariadb-backup-20210617175900",
      "state": "completed",
      "stateUnready": [],
      "bytesDone": 0,
      "percentDone": 100,
      "metadata": {
        "labels": [],
        "creationTimestamp": "2021-06-17T17:59:09Z",
        "modificationTimestamp": "2021-06-17T17:59:09Z",
        "createdBy": "fb093413-b6fc-4a64-a48a-afc32ada8537"
      }
    }
  ],
  "metadata": {}
}
----