---
sidebar: sidebar 
permalink: workflows/wf_unmanage_app.html 
keywords:  
summary:  
---
= Annullare la gestione di un'applicazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi rimuovere un'applicazione gestita quando non è più necessaria. La rimozione di un'applicazione gestita elimina anche le pianificazioni associate.



=== Prima di iniziare

È necessario disporre dell'ID dell'applicazione gestita che si desidera annullare. Se necessario, è possibile utilizzare il flusso di lavoro link:wf_list_man_apps.html["Elencare le applicazioni gestite"] per individuare l'applicazione.

I backup e le snapshot dell'applicazione non vengono rimossi automaticamente quando vengono eliminati. Se non sono più necessari backup e snapshot, è necessario eliminarli prima di rimuovere l'applicazione.



=== 1. Applicazione non gestita

Eseguire la seguente chiamata API REST.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| ELIMINARE | /Accounts/{account_id}/k8s/v1/managedApps/{managedApp_id} 
|===


===== Parametri di input aggiuntivi

Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| id app gestito | Percorso | Sì | Identifica l'applicazione gestita da rimuovere. 
|===


===== Esempio di curl: Rimuovere un'applicazione gestita

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----